apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-one-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/OkkarMin/cluster-manifests-repo"
    targetRevision: HEAD
    path: kubernetes-basic-yaml/stg/app-one
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
