apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-one-stg-web-server
  namespace: stg
  labels:
    app: app-one-stg-web-server
spec:
  selector:
    matchLabels:
      app: app-one-stg-web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: app-one-stg-web-server
    spec:
      containers:
        - name: app-one-stg-web-server
          image: public.ecr.aws/t2q1c3h9/app-one:latest
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: stg
            - name: APPNAME
              value: demo-app-for-teleport
          ports:
            - containerPort: 80
      restartPolicy: Always
