# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-one-stg-ingress
  namespace: stg
spec:
  ingressClassName: nginx
  rules:
    - host: app-one.okkarmin.com
      http:
        paths:
          - path: /stg
            pathType: Prefix
            backend:
              service:
                name: app-one-stg-service
                port:
                  number: 9000
