apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two-prod-web-server
  namespace: prod
  labels:
    app: app-two-prod-web-server
spec:
  selector:
    matchLabels:
      app: app-two-prod-web-server
  replicas: 1
  template:
    metadata:
      labels:
        app: app-two-prod-web-server
    spec:
      containers:
        - name: app-two-prod-web-server
          image: public.ecr.aws/t2q1c3h9/app-two:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: prod
            - name: APPNAME
              value: app-two
          ports:
            - containerPort: 80
      restartPolicy: Always
